security:
    password_hashers:
        App\Infrastructure\Identity\Security\SecurityUser:
            algorithm: argon2id

    providers:
        app_utilisateurs:
            id: App\Infrastructure\Identity\Security\UtilisateurProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern: ^/api/login
            stateless: true
            provider: app_utilisateurs
            json_login:
                check_path: /api/login_check
                username_path: email
                password_path: motDePasse
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            login_throttling:
                max_attempts: 5
        api:
            pattern: ^/api
            stateless: true
            provider: app_utilisateurs
            jwt: ~

    # Note : seule la *première* règle correspondante s'applique.
    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/docs, roles: PUBLIC_ACCESS }
        - { path: ^/api/thematiques, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            App\Infrastructure\Identity\Security\SecurityUser:
                algorithm: argon2id
                time_cost: 3
                memory_cost: 10
